### ISSUE TITLE
emmm，一不小心玩出了bug。。。

### ISSUE THREAD

**Issue by DancingSnow0517** [ToKiNoBug/SlopeCraft#1]
![image](https://user-images.githubusercontent.com/60736156/122657424-0f7bc000-d196-11eb-8234-8517b4baae49.png)
在第5步调语言，然后清零了

**Comment by ToKiNoBug** [comment]
emmmmmmmm窝觉得这个bug不算严重，也不知道能怎么修……就这样搁着吧

**Comment by DancingSnow0517** [comment]
emmm，那透明通道的那个问题呢。。。看我另一个issues
