### ISSUE TITLE
[猜想建议] 关于 SlopeCraft 在 Bedrock 上应用的方法的猜想

### ISSUE THREAD

**Issue by gggxbbb** [ToKiNoBug/SlopeCraft#11]
Minecraft 提供了一个命令 `/function` ([wiki](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/function)), 可执行由 行为包 ([wiki](https://minecraft.fandom.com/zh/wiki/%E9%99%84%E5%8A%A0%E5%8C%85)) 提供的 `mcfunction` 文件 ([wiki](https://minecraft.fandom.com/zh/wiki/%E5%87%BD%E6%95%B0%EF%BC%88%E5%9F%BA%E5%B2%A9%E7%89%88%EF%BC%89)), 或许可以使用程序生成大量的 `setblock` 命令, 封装为行为包来实现在 Bedrock 上生成地图画.

使用 `/function` 命令需激活作弊.

虽说效果估计不会很好, 但至少能用.

**Comment by ToKiNoBug** [comment]
以前用的就是这个方法，甚至直到现在都保留着这个界面（即没有删除也没有实现）但我看了一个介绍基岩版地图的视频，我怀疑java和基岩版的地图机制可能不一样。

**Comment by gggxbbb** [comment]
应该是不同的，be似乎用的是mj自己改过的leveldb来存储地图数据。

**Comment by gggxbbb** [comment]
https://github.com/Mojang/leveldb-mcpe

**Comment by gggxbbb** [comment]
![image](https://user-images.githubusercontent.com/39845709/127739326-2d36792a-8b73-485d-b0e0-de59b5f1d81e.png)
你这也太臭了 （手动狗头

**Comment by gggxbbb** [comment]
我尝试着使用 NBTExplorer 和 MCC Chest Tool 将 Slope Craft 生成的 地图文件 (map_*.dat) 一直到 be 上，发现 be 地图(128*128)的 colors 有 65536 bytes 而非 je 的 16384 bytes。同时我也发现 MCC Chest Tool 可以直接导入图片来覆盖已有地图，可惜它并不开源。

**Comment by gggxbbb** [comment]
be 地图的 colors 似乎是根据 RGBA 来定义的

**Comment by ToKiNoBug** [comment]
那么be的地图就更好了，理论上没有颜色限制。

**Comment by ToKiNoBug** [comment]
> ![image](https://user-images.githubusercontent.com/39845709/127739326-2d36792a-8b73-485d-b0e0-de59b5f1d81e.png)
> 你这也太臭了 （手动狗头
> 
> 此条有图，无图请魔法

哈哈，故意的

**Comment by gggxbbb** [comment]
https://evax.top/2021/08/01/high-be-map-drawing.html 尝试了一下在 be 中实现地图画

**Comment by ToKiNoBug** [comment]
我想了想，基岩版和java版的区别实在太巨大了，加入对基岩版的支持会很困难，让整个软件的操作更难懂、界面更复杂。不如以你现有的成果单独给基岩版开发一个。
