### ISSUE TITLE
3.4.3的版本中好像沒有exe的檔案

### ISSUE THREAD

**Issue by F4A11CherryHoi** [ToKiNoBug/SlopeCraft#12]
ToKiNoBug您好,
![image](https://user-images.githubusercontent.com/72715916/127839629-8d7b6491-e673-4505-a4d5-b6a740a09627.png)
这是我打開3.4.3的檔案後的截屏,裡面好像沒有找到exe的檔案.
我不知道是我的問題還是我找不道
如看到請回覆.
謝謝您的創作
我來自英國,如果中文難以看懂,請見諒

**Comment by gggxbbb** [comment]
Are you sure that the file you downloaded is `SlopeCraft.v3.4.3.7z`, not `Source Code`?

**Comment by ToKiNoBug** [comment]
That's because you downloaded my source code instead of release. Please download in Release. Wish you can get on well with github.
