### ISSUE TITLE
你这个库……它能打Jar包吗，就像JavaFX的库一样

### ISSUE THREAD

**Issue by TheSmileCat** [ToKiNoBug/SlopeCraft#13]
我以为这个项目是Java写的，寻思能不能改改弄成Spigot插件装在自己服务器上（非商业），打开一看，傻眼了，C写的
Spigot有个插件，叫ImageOnMap，只支持到1.15.x，我1.17仍然在用，bug百出苟延残喘（无法正常使用），考虑换掉，所以来看看来着，发现语言不一致，我做不到……但是有dll打jar包的先例（
所以来这里留个言（狗头
不过程序带有的3个功能也足够我自己用了……第三个功能我似乎可以用来暴力改服务器文件的样子（狗头），反正都是.dat地图文件
最后：感谢作者的分享。

**Comment by ToKiNoBug** [comment]
我是完全不会java的……不知道java能不能和c++联合编程？只要你告诉我给c++的接口该怎么设计，我可以尝试做出接口来。如果java不行那也可以试试python

**Comment by ToKiNoBug** [comment]
（另外它不是一个库，是一个完整的程序……）

**Comment by ToKiNoBug** [comment]
总之我很乐意让SlopeCraft拥有插件版本，但需要有人告诉我接口的编写方式

**Comment by ToKiNoBug** [comment]
P.S.：语言不是c，是c++。项目被github认为是c编写的是因为直接包含了zlib的源代码，zlib是c写的，而且代码量比我的略多……

**Comment by gggxbbb** [comment]
@ToKiNoBug 你或许可以使用git submodule来引入zlib，这样应该不会造成语言识别问题

**Comment by ToKiNoBug** [comment]
现在正在做的一件是就是重整代码，把前端和后端分离，让后端成为可以脱离qt环境独立运行的内核。等内核调试完毕了，应该就可以用cpp与java联合编程，调用cpp的内核接口编写插件了

**Comment by ToKiNoBug** [comment]
内核已经被重构成了一种库的形式，应该可以通过联合编程调用。
