### ISSUE TITLE
[功能请求] 希望支持原版结构方块文件格式

### ISSUE THREAD

**Issue by YueLengM** [ToKiNoBug/SlopeCraft#15]
现在的投影导出方式只有 `litematic`，这就意味着对于 forge 端来说，直接放弃了 1.12.2 之后的版本。希望能添加对原版[结构方块](https://minecraft.fandom.com/zh/wiki/%E7%BB%93%E6%9E%84%E6%96%B9%E5%9D%97%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F)的支持。

另外也希望能增加一些新方块（比如 [MapartCraft](https://github.com/rebane2001/mapartcraft) 支持的更便宜的地毯、半砖等）和提供禁用[末影人能搬动的方块](https://minecraft.fandom.com/zh/wiki/%E6%9C%AB%E5%BD%B1%E4%BA%BA#.E7.A7.BB.E5.8A.A8.E6.96.B9.E5.9D.97)的选项。

**Comment by gggxbbb** [comment]
结构方块不够塞吧，单个48*48*48太小了，得一大坨文件才行 :(

**Comment by YueLengM** [comment]
> 结构方块不够塞吧，单个48_48_48太小了，得一大坨文件才行 :(

事实上结构方块在加载 nbt 文件时不会检查大小，多大都会加载的，48 只是方块存储和选区时候的限制。

**Comment by ToKiNoBug** [comment]
是个好的建议，我研究一下结构方块的编码格式。即将发布的v3.5不会加入这个功能，希望能在v3.6完成

**Comment by ToKiNoBug** [comment]
已经实现了。但原版结构方块文件使用的是类似于稀疏矩阵的“坐标-方块”对存储的，占用空间很大，哪怕把所有空气方块都换成结构空位（可以压缩掉90%的空间），它的文件量仍然远大于投影文件。我很怀疑mc能否正常加载这么大的结构

**Comment by YueLengM** [comment]
我加载过 256*256 的像素画，文件大概 500KB 左右，没什么问题。

**Comment by ToKiNoBug** [comment]
> 可以考虑添加.schematic文件支持，这样高版本forge端可以使用worldedit导入

.schematic格式有相关的教程/文档吗？我自己看不懂
