### ISSUE TITLE
导出时出现奇怪的问题，直接软件就挂了

### ISSUE THREAD

**Issue by 2651084156** [ToKiNoBug/SlopeCraft#2]
![屏幕截图 2021-06-25 220815](https://user-images.githubusercontent.com/69307837/123445511-8851a080-d60a-11eb-864d-26c617d893f0.png)
只有一个这样的窗口

**Comment by ToKiNoBug** [comment]
这个是潜藏的矩阵越界问题，可能是导出为地图文件时，图片尺寸不为128的整倍数导致的越界；也有可能是v3.1的时候没有阻止用户试图将“不可实装的地图画”导出为投影导致的张量越界。v3.3已经修复了这些个bug，很快就会发布。

**Comment by ToKiNoBug** [comment]
v3.3已修复，如果再次出现请继续反馈
