### ISSUE TITLE
["Bug反馈"] 无法禁用部分颜色

### ISSUE THREAD

**Issue by MarinaMarissa** [ToKiNoBug/SlopeCraft#22]
### 我的操作
详见视频

### 我认为应当发生的事情
禁用rawIron颜色

### 实际上发生的事情
没有禁用指定颜色

### 我导入到SlopeCraft中的原图
你导入到SlopeCraft中的原图。直接放原图，不要把原图缩放之后再上传。
![像素画](https://user-images.githubusercontent.com/61768909/137608263-4fb75363-40dc-4a71-9f47-fc37c31c21a9.jpg)

### 其他

视频https://user-images.githubusercontent.com/61768909/137608268-576ab424-180d-4aef-be9d-cb5cf3e85fb7.mp4
实际上其他颜色有时候也不能被禁用

**Comment by ToKiNoBug** [comment]
有一个毛招儿，把版本选到1.16。低版本的投影照样能被高版本的litematica加载

**Comment by MarinaMarissa** [comment]
> 有一个毛招儿，把版本选到1.16。低版本的投影照样能被高版本的litematica加载

实际上1.16也有部分颜色无法禁用。。。
