### ISSUE TITLE
功能请求 希望支援分割檔案(1x1 litematic)

### ISSUE THREAD

**Issue by patyhank** [ToKiNoBug/SlopeCraft#25]
如標題 希望添加支持 以128x128為單位的分割檔案
並以壓縮檔格式輸出

**Comment by ToKiNoBug** [comment]
我不清楚你说的“档案”和“压缩档”指的是什么。

**Comment by patyhank** [comment]
將大圖拆成以128×129為單位的litematic檔案
然後再壓縮成zip這樣

**Comment by ToKiNoBug** [comment]
可以说一说这样做的用处/意义吗？我不理解为什么需要这个功能

**Comment by patyhank** [comment]
在多人伺服器上會卡到其他人的領地
還有就是藍圖驗證缺失的區塊會跑很久

**Comment by ToKiNoBug** [comment]
可以用图像处理软件先把图像分割成128*128的单元，再挨个做成地图画。
另外现在还在设计批量处理功能，如果实现了，也会很有帮助。

**Comment by ToKiNoBug** [comment]
新版本加入了图片分块和批量处理功能，可以高效完成你想要的功能。
