### ISSUE TITLE
材料列表

### ISSUE THREAD

**Issue by JavaCoffeePro** [ToKiNoBug/SlopeCraft#26]
像SpriteCraft那样的材料列表，如果可以，在`导出为`添加"导出成材料列表表格"的按钮

**Comment by JavaCoffeePro** [comment]
对于生存来说，准备好材料再开工。果然还是比一边造一边收集材料更合理。
材料列表可以让我知道，这种材料是否收集足够

**Comment by JavaCoffeePro** [comment]
或许应该放在更显眼的位置……

**Comment by ToKiNoBug** [comment]
之前还从来没遇到过这个问题，因为litematica mod自己有输出材料列表的功能
