### ISSUE TITLE
[Bug反馈]导出为地图文件时透明色无效

### ISSUE THREAD

**Issue by August7** [ToKiNoBug/SlopeCraft#27]
### 我的操作
在设置地图方块列表的时候透明色为不可选中的状态；导出为地图文件时透明被当成了白色。
![QQ截图20220109000643](https://user-images.githubusercontent.com/8176495/148651785-add4c313-3c2c-4536-a1c1-b8c29c5fc9a5.png)

### 我认为应当发生的事情
![QQ截图20220109002520](https://user-images.githubusercontent.com/8176495/148651810-a9ecfba5-6826-4ca3-8f0b-fe41d27e6210.png)

### 实际上发生的事情
![QQ截图20220109002546](https://user-images.githubusercontent.com/8176495/148651825-19a5907a-7ba8-4e34-920e-5324b5806951.png)

### 我导入到SlopeCraft中的原图
![test](https://user-images.githubusercontent.com/8176495/148651831-db947325-5bfb-452d-bfae-5bf3abb9fa58.png)

**Comment by ToKiNoBug** [comment]
导入图片之前记得点“设置”，那里面有自定义的透明色处理策略。
