### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by 183954477** [ToKiNoBug/SlopeCraft#28]
## 反馈Bug
win7 在3.6中 打开主程序 显示“无法定位程序输入点 CreateEventW 于动态链接库 api-ms-win-core-synch-l1-2-0.dll上”

3.5可以打开

**Comment by ToKiNoBug** [comment]
这个是qt 6.2.0与win7的不兼容。我是在win10上编译发布的，但看来win7上用不了。

我现在升级到了qt 6.2.1，我尽快放出release，希望qt有解决这个问题。实在不行就用回qt 6.0.2

当然其实还有另一个方案：你clone源码，然后按照[编译说明](https://github.com/ToKiNoBug/SlopeCraft/blob/main/docs/HowToCompile.md)在自己的平台上编译发布，这样更稳妥

**Comment by AbrasiveBoar902** [comment]
qt 6.2似乎确实与win7不兼容，我也遇到了一样的问题，官网的支持系统没有win7

**Comment by wpcwzy** [comment]
经虚拟机测试，Windows 7 SP1（内部版本7601）可以正常运行。只是启动时自动更新会报json解析错误

**Comment by ToKiNoBug** [comment]
> 经虚拟机测试，SlopeCraft 的最新版本 https://github.com/ToKiNoBug/SlopeCraft/releases/tag/v3.6.1 在Windows 7 SP1（内部版本7601）上可以正常运行。只是启动时自动更新会报json解析错误

能正常运行就好。json解析错误应该是自动检查更新失败导致的，不用在意。
