### ISSUE TITLE
求作者更新1.18，谢谢！

### ISSUE THREAD

**Issue by lty12b9b0a1** [ToKiNoBug/SlopeCraft#29]
1.17的投影文件1.18似乎用不了

**Comment by ToKiNoBug** [comment]
我在想要不要等1.18的litematica mod出现稳定版

**Comment by ToKiNoBug** [comment]
或者说现在这个v1.18.1-0.9.0是稳定版吗

**Comment by lty12b9b0a1** [comment]
> 或者说现在这个v1.18.1-0.9.0是稳定版吗

litematica 目前似乎只有fabric支持1.18。forge只有1.16。然后我个人服务器这边用的是forge，所有没有用这个mod
不过目前已有一些其他 支持投影文件 的建造mod更新到forge1.18了。比如worldedit，应该是稳定版。
我个人理解是投影文件应该不同版本区别不大，但实际上是现在是：能list 出来，但一load就显示找不到文件。
其实感觉如果知道litematica投影文件的结构可以自己手动改改，可惜我本人对mod研究不多。
或者可能是worldedit只支持schematic投影文件，不支持litematica，不过我先前看一些视频这两种文件似乎都能用。

**Comment by ToKiNoBug** [comment]
合着原来你是用word eidt打开litematic然后问我支持1.18………

这不是1.17和1.18的问题，这是we和litematica的问题，汗

试试导出成.nbt格式，原版结构方块不依赖任何mod，we总归支持吧，

**Comment by lty12b9b0a1** [comment]
感谢感谢，我之前确实看worldedit有schematic和litematic混用的，以为都支持
