### ISSUE TITLE
[功能请求]添加色彩抖动算法

### ISSUE THREAD

**Issue by noeru-desu** [ToKiNoBug/SlopeCraft#3]
我测试了所有颜色数量、颜色空间，在最后预览此图片时，都出现了几乎全是灰色的情况(蓝毛变灰毛)
<img width="128" alt="64978502_p24" src="https://user-images.githubusercontent.com/52559014/123512179-9c53db80-d6b8-11eb-9e2a-a5ebb1a78bab.png">
<img width="512" alt="64978502_p24" src=https://user-images.githubusercontent.com/52559014/123512259-15533300-d6b9-11eb-82fd-13a5422b6722.png>
<img width="512" alt="64978502_p24" src=https://user-images.githubusercontent.com/52559014/123529906-829dad00-d727-11eb-925c-3c7393db3c92.png>
_使用232色的效果，其他效果不好的颜色空间略过_
**我个人看来，这是因为MC中不同蓝色太少导致的，在SlopeCraft中，仅有的深蓝和浅蓝分配给了头发的阴影部分和眼睛部分
要解决此问题，个人认为最好的方法就是使用颜色抖动，SpriteCraft就使用了此方法，没有出现大面积灰色的情况**
<img width="512" alt="64978502_p24" src="https://user-images.githubusercontent.com/52559014/123512973-01113500-d6bd-11eb-8d18-7639c5ca9fba.png">
_保证对比的严谨性，我将SpriteCraft的可用方块设置为与SlopeCraft相同，SpriteCraft所没有的方块使用相近颜色方块代替_
虽然有时背景会出现变花的情况，但可以通过将背景改为纯色的方法解决(我以前在服务器实装另一个像素画就是这样的)
另外附上一个SpriteCraft不使用颜色抖动的生成效果图
<img width="512" alt="64978502_p24" src="https://user-images.githubusercontent.com/52559014/123512898-9b24ad80-d6bc-11eb-9185-378ae82d3a0f.png">
**可以看出不开启颜色抖动，SpriteCraft的效果与SlopeCraft几乎一致，甚至没有SlopeCraft的效果好**
### 最后感谢作者编写的SlopeCraft

**Comment by sophie-desu** [comment]
附上另一个作者不详的软件的生成效果
![屏幕截图 2021-06-26 204023](https://user-images.githubusercontent.com/52559014/123513258-bf818980-d6be-11eb-9c99-f797095a9268.png)
提供了多种抖动算法，随便使用了一个进行演示

**Comment by ToKiNoBug** [comment]
最近正在学颜色抖动算法。另外如果我最后只能实现一种或两三种算法，有比较好的算法推荐吗？

**Comment by noeru-desu** [comment]
我个人也没有深入研究各个抖动算法的差别，抱歉。
在英文Wikipedia上面有较为完整的说明：[Dither条目的Algorithms部分](https://en.wikipedia.org/wiki/Dither#Algorithms)

**Comment by noeru-desu** [comment]
在我用过的抖动算法里面，普遍来说[Floyd–Steinberg]https://en.wikipedia.org/wiki/Floyd%E2%80%93Steinberg_dithering算法的效果较好，速度也较快。

**Comment by ToKiNoBug** [comment]
我实现了任何一种色彩空间的Floyd-Steinberg算法，但很奇怪的是它几乎没有任何变化。抖动带来的混色似乎直接被自己平均掉了。我仔细对照了网上很多代码，没有发现什么错误，但就是几乎没有效果。抖动后的图片和原图几乎完全一致（仅在边缘处不同），连混色都完全没有表现出来。

**Comment by ToKiNoBug** [comment]
我试了试你的图片，先将它按像素转化为地图色，也就是几乎全都是灰色的图像；随后我使用floyd-steinberg算法把转化前后的误差扩散，但结果是——它几乎把图像还原回去了。然后这个几乎完全还原的图像再按像素转化成地图画，效果几乎没有任何改善……

**Comment by noeru-desu** [comment]
![ffmpeg的Floyd–Steinberg](https://user-images.githubusercontent.com/52559014/126976398-9cd49585-4d58-48d2-8bbc-0eb0863ae79d.png)
这个是我使用ffmpeg生成的一张
(好像调色板有点问题，可用颜色比较少)

**Comment by noeru-desu** [comment]
也是使用的Floyd–Steinberg算法

**Comment by noeru-desu** [comment]
作者可以试试使用[FFmpeg](https://ffmpeg.org/ffmpeg.html)
(这样就不用自己写算法了)

**Comment by ToKiNoBug** [comment]
但ffmpeg是不是只用了rgb啊……虽然算法目前没成功但我觉得在lab色彩空间里扩散误差会更合理，毕竟lab的三个分量几乎无关，但rgb的三个分量高度相关

**Comment by ToKiNoBug** [comment]
成功了，至少rgb的抖动算法成功了。其他色彩空间里的因为色彩空间转换公式可能有错，效果目前不是很好。
![Lab抖动](https://user-images.githubusercontent.com/62002934/126988712-5eb3b5e2-9211-45db-93c9-288aa2fa6415.png)
![RGB抖动](https://user-images.githubusercontent.com/62002934/126988716-3811ba9b-31d4-4717-bec6-57a77f096bb6.png)

**Comment by ToKiNoBug** [comment]
可惜勾线被抖成了蓝色……
