### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by 21Yangming** [ToKiNoBug/SlopeCraft#32]
### 我的操作
使用Slopecraft时软件生成的地图画预览无问题，当粘贴投影到世界上时会出现大量的地图空缺，并且并不是一张地图画的问题，而是很多的问题（我批量生成了40张，全部都是有空缺）
### 我认为应当发生的事情
SlopeCraft应当生成如软件上一致的地图画

### 实际上发生的事情
出现大量空缺

### 我导入到SlopeCraft中的原图
你导入到SlopeCraft中的原图。直接放原图，不要把原图缩放之后再上传。
![75e538b3-6976-4592-a59d-715d923b0d87_](https://user-images.githubusercontent.com/103307321/162562850-6ac4e2e9-e791-475d-96d6-0dc4ae3f9183.png)这个是原图
![5fc1d12210a6367329bc08285a802cc](https://user-images.githubusercontent.com/103307321/162562853-86c07317-b737-47db-835b-985766382f5e.png)这个是生成之后的图

[text5.zip](https://github.com/ToKiNoBug/SlopeCraft/files/8456504/text5.zip)投影文件压缩包

### 其他
任何其他关于这个bug的话。

**Comment by ToKiNoBug** [comment]
你使用的SlopeCraft是哪个版本？对应的游戏版本是什么？地图画类型选的是什么？

**Comment by ToKiNoBug** [comment]
按着模板填你也没写清楚具体操作啊，不怕啰嗦越啰嗦越好……最重要的三个信息一应具缺。看起来这是非常典型的方块id出错，游戏版本是最不可或缺的信息

**Comment by ToKiNoBug** [comment]
靠，还真是挺严重的问题……所有1.12至1.13方块id没变的方块，在投影里id都是空白的

**Comment by ToKiNoBug** [comment]
先暂且用v3.7凑合一下吧，主体功能没有差异的

**Comment by AbrasiveBoar902** [comment]
4.0.1已修复
https://wwn.lanzout.com/iGhwQ02z4cla
密码:fgy3
（这锅得给ToKiNoBug背[doge]他告诉我kernel能处理idOld为空的情况，我没写特判
