### ISSUE TITLE
其他

### ISSUE THREAD

**Issue by wly1998** [ToKiNoBug/SlopeCraft#33]
教程界面404了，希望可以补档。谢谢。

**Comment by gggxbbb** [comment]
[教程仓库](https://github.com/ToKiNoBug/SlopeCraftTutorial) 目录结构发生了变化，本仓库的 README暂未同步这些更改，你可以前往 <https://tokinobug.github.io/SlopeCraftTutorial/> 查看使用教程。

**Comment by gggxbbb** [comment]
#34

**Comment by ToKiNoBug** [comment]
> 教程界面404了，希望可以补档。谢谢。

最新的教程pdf都在压缩包里和软件一起提供的
