### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by 0x1a551e2** [ToKiNoBug/SlopeCraft#35]
## 反馈Bug
批量模式多线程处理时输出顺序与输入顺序不同
推测为不同线程处理时未考虑输入顺序关系

### 我的操作
批量模式8线程处理一些图片
设置为纯文件地图画，RGB+，抖动仿色

### 我认为应当发生的事情
图片按输入的顺序被处理为顺序相同的dat文件

### 实际上发生的事情
导出的dat文件顺序与输入顺序不同

### 我导入到SlopeCraft中的原图
![image](https://user-images.githubusercontent.com/104710863/166135648-3c95c2b2-4bdb-4c95-9be6-023d85691b6e.png)

![f0000](https://user-images.githubusercontent.com/104710863/166135653-332cae45-9cf0-442e-ad30-6a6205a5883e.png)

导入图片较多，仅展示一张
均为512*384分辨率，32位png图片，含alpha通道但无透明部分

### 其他
这里所说的是 不同图片对应的地图的顺序与输入不同，同一张图片导出的多张地图顺序没有问题

**Comment by AbrasiveBoar902** [comment]
emm确实设计的时候没有考虑到顺序的问题，因为刚开始没考虑视频。我有时间去修一下bug吧（

**Comment by AbrasiveBoar902** [comment]
你是使用文件夹方式导入的，你说的顺序是按照文件名字典序还是什么其他的顺序？

**Comment by ToKiNoBug** [comment]
已修复（https://github.com/ToKiNoBug/SlopeCraft/releases/tag/v4.0.2）
