### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by 0x1a551e2** [ToKiNoBug/SlopeCraft#36]
**建议添加批量模式下填写起始序列号的功能**
批量模式导出地图文件时无法填写起始序列号，且会覆盖文件夹内原有文件

**Comment by AbrasiveBoar902** [comment]
已实现，等待发布

**Comment by ToKiNoBug** [comment]
> 已实现，等待发布

最近忙的焦头烂额一直没顾得上，现在已发布（https://github.com/ToKiNoBug/SlopeCraft/releases/tag/v4.0.2）
