### ISSUE TITLE
跟进1.19要不要等正式版？

### ISSUE THREAD

**Issue by ToKiNoBug** [ToKiNoBug/SlopeCraft#39]
现在跟进1.19的工作基本上只差1.19的版本号，新方块的基色基本都测过了也都输进FixedBlockList.json了，源代码上需要做的更改不多。要不要抢先于正式版发布支持1.19的slopecraft？想听听大家的建议。

如果等，那就是等到mojang发了1.19第一个正式版就发布；
如果不等，就看这周四mj发的预览版，用它的版本号写进源码里，直接编译发布

**Comment by Cubik65536** [comment]
Mojang 在现在这个阶段应该已经不会怎么改变方块的设计与颜色了，我觉得是可以提前发布的，就算出现了较小的兼容性问题也可以通过小 patch 解决

**Comment by ToKiNoBug** [comment]
好，那我就抢先了
