### ISSUE TITLE
为啥对带有透明通道的图片不友好？

### ISSUE THREAD

**Issue by DancingSnow0517** [ToKiNoBug/SlopeCraft#4]
![image](https://user-images.githubusercontent.com/60736156/123530559-72d59700-d72e-11eb-8813-3cb93e73e286.png)
会有原本透明的地方出现奇奇怪怪的颜色
![11111111](https://user-images.githubusercontent.com/60736156/123530567-88e35780-d72e-11eb-8bd6-d782c9c29c64.png)
原图

**Comment by ToKiNoBug** [comment]
透明区域多出来的颜色是图片自带的，也许是画师的误操作，只是因为完全透明而被掩盖了；但slopecraft完全忽视了透明度，因此让这些”隐藏的颜色“显现了出来。新版已经修复了这个bug，测试完成后很快就会发布

**Comment by DancingSnow0517** [comment]
难道是ps的问题？我这图弄好就是全透明了，没别的透明度100的颜色吧

**Comment by ToKiNoBug** [comment]
> 难道是ps的问题？我这图弄好就是全透明了，没别的透明度100的颜色吧

我认为是一些全透明的像素仍然具有rgb颜色，但被透明所掩盖，v3.2及以前的版本直接忽视透明度，导致这些被掩盖的颜色显现出来。现在v3.3已经把透明的部分全都替换成白色了。

**Comment by DancingSnow0517** [comment]
能不能把透明部分改为无方块？或者添加一个设置？

**Comment by ToKiNoBug** [comment]
这是个挺头疼的问题，在平板和立体地图画里把透明像素处理成空气只会让底下的方块显示出来，在纯文件地图画里透明的像素也只会透出物品展示框的底色……我不知道换成空气能满足什么样的用途？铺在不规则空置域地板的像素画吗？

**Comment by DancingSnow0517** [comment]
对的，现在是手动扣qwq

**Comment by ToKiNoBug** [comment]
> 对的，现在是手动扣qwq

已经在改了。我设想了几个处理透明和半透明像素的方法，正在逐一实现。应该会包含在v3.4里发布吧，现在发的只是一个预览。

**Comment by ToKiNoBug** [comment]
新发布的v3.4 RC1中已经加入了可选的详细的透明像素处理方法，现在纯透明像素可以直接替换为空气。如果有任何问题欢迎反馈
