### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by andogy** [ToKiNoBug/SlopeCraft#42]
## 反馈Bug
最新版本(v3.8.0)中7z不包含所需的dll

### 我的操作
打开SlopeCraft.exe

### 我认为应当发生的事情
开启Gui

### 实际上发生的事情
提示缺少Qt6Network和Libgomp-1的dll

**Comment by ToKiNoBug** [comment]
没想到这dll也会缺……我已经补全了dll了，重新下载就行。
