### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by MadCreeper** [ToKiNoBug/SlopeCraft#44]
### 我的操作
仔细描述你的操作，越详细越好。不怕繁琐，就怕缺漏。
导入任何一张图片，选择平板地图画，1.19版本。查看方块列表
### 我认为应当发生的事情
描述你期望中SlopeCraft应当出现的响应。
蛙明灯，潜声系列方块可以选择
### 实际上发生的事情
描述SlopeCraft实际上发生的响应。**不要忽略任何报错信息，哪怕你看不懂它。**最好有截图。
1.19, 1.18, 1.17更新的方块不可选（蛙明灯，潜声系列方块等）
![image](https://user-images.githubusercontent.com/33979935/170830902-374c18d0-0784-4dc8-a78e-377a014a0c6b.png)
![image](https://user-images.githubusercontent.com/33979935/170830947-9cf27118-68db-4225-a623-a6a9d5c4077d.png)

### 我导入到SlopeCraft中的原图
你导入到SlopeCraft中的原图。直接放原图，不要把原图缩放之后再上传。
应该和导入的图片无关。
![QQ图片20220406165328](https://user-images.githubusercontent.com/33979935/170830930-128edc48-3468-4705-8a46-666ed4692d3b.jpg)

### 其他
任何其他关于这个bug的话。

**Comment by ToKiNoBug** [comment]
我已经复现出来了。奇怪，这个bug我应该是已经修了的啊，为什么还在？

**Comment by ToKiNoBug** [comment]
已修复
