### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by 21Yangming** [ToKiNoBug/SlopeCraft#45]
平面地图画可以弄和SpritecraftFull一样的那种原理图吗，就是图片的那种形式，就和下图一样的，因为有时候服务器不能加装投影文本，弄地图画会麻烦，拜托了
![Splited_1_1](https://user-images.githubusercontent.com/103307321/178511579-5f0dd900-29e3-4c4a-afa5-6563f79d043b.png)

**Comment by ToKiNoBug** [comment]
我会试着实现这个功能

**Comment by ToKiNoBug** [comment]
已经实现了，明天发布新版

**Comment by ToKiNoBug** [comment]
已经实现，已经发布
