### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by l-fog** [ToKiNoBug/SlopeCraft#46]
### 我的操作
仔细描述你的操作，越详细越好。不怕繁琐，就怕缺漏。

在第四步「调整颜色」中，选择算法「HSV」，开启「抖动仿色」，点击「转换为地图画」

### 我认为应当发生的事情
描述你期望中SlopeCraft应当出现的响应。

应该能产生正常的颜色

### 实际上发生的事情
描述SlopeCraft实际上发生的响应。**不要忽略任何报错信息，哪怕你看不懂它。**最好有截图。

颜色产生严重偏差（多张图片测试，结果相同）

![image](https://user-images.githubusercontent.com/54096848/180103379-5166a5c7-fe52-47d6-8ba8-519e13e12365.png)

### 我导入到SlopeCraft中的原图
你导入到SlopeCraft中的原图。直接放原图，不要把原图缩放之后再上传。
![FUkehymWAAA0Rpa](https://user-images.githubusercontent.com/54096848/180103408-0613b711-4976-4a11-84a0-d259808798ff.jpg)

### 其他
任何其他关于这个bug的话。

**Comment by ToKiNoBug** [comment]
感谢反馈，这个错误比较尴尬，它一直存在，但我一直不知道怎么修……

**Comment by AbrasiveBoar902** [comment]
笑死，HSV
这是个特性[doge]

**Comment by ToKiNoBug** [comment]
刚才已经修好了，明天发布新版

**Comment by ToKiNoBug** [comment]
已经修复，已经发布了
