### ISSUE TITLE
无法导出为投影

### ISSUE THREAD

**Issue by Wlz2022** [ToKiNoBug/SlopeCraft#47]
我的图片像素大小2000*2000，不知道为什么不能导出为投影。换了好几个像素大小的图片貌似都不行……最小的试了一下300*300的，不过还是不能导出为投影……能不能解答一下=-=谢谢啦~版本是最新版本

**Comment by ToKiNoBug** [comment]
这个尺寸的图片如果做成平板的应该有希望，立体的肯定不行，内存不够的

**Comment by Wlz2022** [comment]
换成平板好像！就可以了！谢谢！辛苦啦

**Comment by ToKiNoBug** [comment]
图片还是非常大，我写slopecraft的时候没有考虑到特别大的图
