### ISSUE TITLE
HSV仿色算法出现问题

### ISSUE THREAD

**Issue by vibe-Chen** [ToKiNoBug/SlopeCraft#48]
### 我的操作
导入图片：（格式：PNG，创建软件：mspaint.exe）
![Noel_128](https://user-images.githubusercontent.com/84615342/182859869-da3637f7-bdfd-429c-90da-1a7dc7b4c606.png)
地图画版本/类型：1.19/立体
方块列表：Elegant
调整颜色：HSV，抖动仿色开启

### 我认为应当发生的事情
比该图片（HSV，抖动仿色关闭）更好的结果。
![HSV_off](https://user-images.githubusercontent.com/84615342/182860370-4209284d-a158-4db7-a048-161d64b38280.png)

### 实际上发生的事情
整张图片变成了黄色色调。
![HSV_on](https://user-images.githubusercontent.com/84615342/182860673-dd8089fa-85ab-444d-a852-276560bb475e.png)

### 我导入到SlopeCraft中的原图
![Noel_128](https://user-images.githubusercontent.com/84615342/182859869-da3637f7-bdfd-429c-90da-1a7dc7b4c606.png)

### 其他
~~推测为HSV仿色算法出现问题。~~ 结论已更新。

### 我的操作

导入图片：（格式：PNG，创建软件：Adobe Photoshop CC 2019）
![4_256](https://user-images.githubusercontent.com/84615342/182872543-5a7fcf51-b5e8-49b7-a9a2-88d33c652509.png)
地图画版本/类型：1.19/立体
方块列表：Elegant
调整颜色：HSV，抖动仿色开启

### 我认为应当发生的事情
比该图片（HSV，抖动仿色关闭）更好的结果。
![HSV_off2](https://user-images.githubusercontent.com/84615342/182873081-e33ea0a3-70ea-4867-b994-f43ada0bebec.png)

### 实际上发生的事情
整张图片变成了红色色调。
![HSV_on2](https://user-images.githubusercontent.com/84615342/182873154-9bf5877a-0cfd-4665-ac85-b38082fd5d3d.png)

### 我导入到SlopeCraft中的原图
![4_256](https://user-images.githubusercontent.com/84615342/182872543-5a7fcf51-b5e8-49b7-a9a2-88d33c652509.png)

### 其他
推测为HSV仿色算法部分少写了一个2π，导致颜色全部向红/黄色调集中。
（1/2π=0.159，换算为RGB约为#FFF200）

**Comment by ToKiNoBug** [comment]
感谢你的反馈，我也在琢磨自己的代码，可能确实是少乘了2pi，我再试着修一修吧……
