### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by zsq213** [ToKiNoBug/SlopeCraft#49]
### 我的操作
仔细描述你的操作，越详细越好。不怕繁琐，就怕缺漏。
建造地图画时发现bug，投影文件y轴高度没有超过256
![0811e8708c5d4379be6d3fd66d40be5](https://user-images.githubusercontent.com/96360351/183377865-41a32d66-e977-4a59-9c5f-757e21e1c5f7.jpg)
![微信截图_20220808164311](https://user-images.githubusercontent.com/96360351/183377873-41f06493-7aa0-4687-aa70-946b8e40f284.png)

### 我认为应当发生的事情
描述你期望中SlopeCraft应当出现的响应。
生成完整地图画
### 实际上发生的事情
描述SlopeCraft实际上发生的响应。**不要忽略任何报错信息，哪怕你看不懂它。**最好有截图。
立体地图画有时缺方块
### 我导入到SlopeCraft中的原图
你导入到SlopeCraft中的原图。直接放原图，不要把原图缩放之后再上传。

### 其他
任何其他关于这个bug的话。

**Comment by ToKiNoBug** [comment]
md，这个bug怎么还在啊……我记得自己已经修过了，是v3.8吗？

**Comment by zsq213** [comment]
> md，这个bug怎么还在啊……我记得自己已经修过了
是的 SlopeCraft-v3.8.1

**Comment by zsq213** [comment]
时好时坏的

**Comment by ToKiNoBug** [comment]
你把生成的投影文件/结构方块文件通过邮件发给我吧，tokinobug@163.com

**Comment by zsq213** [comment]
> 你把生成的投影文件/结构方块文件通过邮件发给我吧，[tokinobug@163.com](mailto:tokinobug@163.com)

发过去了

**Comment by ToKiNoBug** [comment]
你发过来的投影是完全正常的，我也复现不出来这个bug

**Comment by ToKiNoBug** [comment]
如果你还留着缺方块的投影，也通过邮件发过来

**Comment by zsq213** [comment]
> 如果你还留着缺方块的投影，也通过邮件发过来

你的mc是什么版本的，我是1.16.5，难道是版本的问题？投影文件如图
![微信截图_20220810105604](https://user-images.githubusercontent.com/96360351/183800283-9e258662-afc5-4650-bf01-54a50a326adc.png)

**Comment by ToKiNoBug** [comment]
我按1.16生成，用的是1.18打开，因为1.16的端删了。现在的问题是我检查了输出的投影文件的nbt，没看出来什么问题，我复现不出来问题。你发给我截图是没用的，我需要用nbt explorer打开，检查一下缺方块的地方本来应该是什么方块，再看看方块表里到底出了什么错，所以我需要投影文件。

**Comment by zsq213** [comment]
破案了，在服务器建的时候有bug，在本地测试的时候没有问题
