### ISSUE TITLE
3.3版本提示缺少libgcc和libstdc相关的dll，无法启动程序

### ISSUE THREAD

**Issue by sophie-desu** [ToKiNoBug/SlopeCraft#5]
![屏幕截图 2021-07-03 195621](https://user-images.githubusercontent.com/52559014/124353396-e26cea00-dc38-11eb-8f32-a04634e6ae5b.png)
![屏幕截图 2021-07-03 195628](https://user-images.githubusercontent.com/52559014/124353398-e3058080-dc38-11eb-94d1-f6cf0eb04c65.png)
3.2版本可正常启动

**Comment by ToKiNoBug** [comment]
尝试重新下载解压。如果还不行，把所有文件夹里的dll复制一份，放在与exe同一个文件夹下。

**Comment by ToKiNoBug** [comment]
谢谢你的反馈，经过检查，3.3的压缩包中确实缺少这两个dll。刚刚更新了v3.3.1，补充了这两个dll，请问现在新版本可以正常运行了吗？

**Comment by sophie-desu** [comment]
可以了，谢谢作者
