### ISSUE TITLE
能否添加导出色板的功能以便于像素画创作？

### ISSUE THREAD

**Issue by fwzuw** [ToKiNoBug/SlopeCraft#51]
如题，我通常不会直接将非像素画转为像素画，而是自行绘制像素画再在 mc 中搭建。以前我使用的是 16 色混凝土，也疑惑过颜色不一样的情况。了解了该工具后我很高兴，但 wiki 上的色板图片被压缩过，我无法处理出正确的颜色。考虑到该工具支持添加新的方块颜色，能否也支持导出色板文件？

#### wiki上被压缩的色板图片，有很多杂色：
![image](https://user-images.githubusercontent.com/48246272/185337643-19c03701-4d61-4234-9311-6e03c6a163b0.png)

#### 我处理后的图片，每种颜色只有一个像素，但与正确的颜色有一定偏差：
![image](https://user-images.githubusercontent.com/48246272/185337512-caa2fa00-70eb-4d75-866e-dfc86d707581.png)

**该像素画软件可以直接从图片中读取色板**，读取顺序为从左到右从上到下，若颜色无法填满最后一行，则会用第一种颜色填充。
#### 软件保存的色板图片：
![image](https://user-images.githubusercontent.com/48246272/185337430-8acc4926-f744-4d36-95a6-e1e66a6822f4.png)

以下是该软件支持的全部色板文件格式，第二种是该软件独有：
![image](https://user-images.githubusercontent.com/48246272/185333005-ad59645c-b898-4c2b-a286-5ca5fd20b67d.png)

**Comment by ToKiNoBug** [comment]
好主意，我会实现这个功能，把可用的颜色输出为一个png图片，每种颜色只占一个像素，当前地图画模式下不可用的颜色设为透明

**Comment by ToKiNoBug** [comment]
我实现了这个功能，目前是导出成16*16像素的图片


![colors_05](https://user-images.githubusercontent.com/62002934/187028924-f8ec95b7-5ff6-4f9c-a7e6-2917485da638.png)

**Comment by fwzuw** [comment]
效果很好
不过有一个比较意外的发现，有部分颜色是相同的，
![image](https://user-images.githubusercontent.com/48246272/187029491-022ddd6a-b162-4cb9-84a7-9ddbf5916537.png)
蓝框标注了两个 52, 52, 52，而在英文 wiki 中第一个应该是 53, 53, 53
我在 3.9.0 中没有找到相关选项，推测实现了该功能的版本还没有发布，因此使用的是这张图片
> ![colors_05](https://user-images.githubusercontent.com/62002934/187028924-f8ec95b7-5ff6-4f9c-a7e6-2917485da638.png)

不清楚是图片被网络压缩过，还是导出时就有问题？甚至往深了想，会不会是计算阴影时就出现了问题？

**Comment by ToKiNoBug** [comment]
> 效果很好 不过有一个比较意外的发现，有部分颜色是相同的， ![image](https://user-images.githubusercontent.com/48246272/187029491-022ddd6a-b162-4cb9-84a7-9ddbf5916537.png) 蓝框标注了两个 52, 52, 52，而在英文 wiki 中第一个应该是 53, 53, 53 我在 3.9.0 中没有找到相关选项，推测实现了该功能的版本还没有发布，因此使用的是这张图片
> 
> > ![colors_05](https://user-images.githubusercontent.com/62002934/187028924-f8ec95b7-5ff6-4f9c-a7e6-2917485da638.png)
> 
> 不清楚是图片被网络压缩过，还是导出时就有问题？甚至往深了想，会不会是计算阴影时就出现了问题？

看来是浮点运算舍入和整数的舍入不一样，出的问题

**Comment by ToKiNoBug** [comment]
我重新设置了色彩源，现在应该已经解决了
![colors_06](https://user-images.githubusercontent.com/62002934/187031333-35577f18-7997-43dc-9751-11c56e34b57e.png)

**Comment by fwzuw** [comment]
> 我重新设置了色彩源，现在应该已经解决了 ![colors_06](https://user-images.githubusercontent.com/62002934/187031333-35577f18-7997-43dc-9751-11c56e34b57e.png)

的确，现在没有相同的颜色了，色板很整齐

不过，我发现深板岩的第三阶颜色从英文 wiki 的 100, 100, 100 改成了中文 wiki 的 86, 86, 86，如果第三阶是 100 的话，第二阶正好是 86，因此我怀疑中文 wiki 上的数据是错的，于是我下载 1.19.2 测试了下
![image](https://user-images.githubusercontent.com/48246272/187032623-c1eb1d5a-fea9-44ad-837a-9f95e5cce107.png)嵌入在超平坦地形里的色彩应是第二阶，相对更高的应在第三阶，虽不清楚为什么和英文 wiki 有细微偏差，但用中文 wiki 上的 86, 86, 86 来做深板岩的第三阶色彩显然是错的

**Comment by ToKiNoBug** [comment]
ok，我再修正一下基色

**Comment by ToKiNoBug** [comment]
我自己在1.19测了一下，也是3个98。最初测基色的时候是在快照里测的，可能mojang后来改了，又改的不大

**Comment by ToKiNoBug** [comment]
现在采用的是测出来的结果（98 98 98），一个图是完整的基色（按1.19纯文件地图画），另一个是可用的基色（按1.19立体地图画且去掉水导出）
![colors_07](https://user-images.githubusercontent.com/62002934/187067930-57126e47-0b2b-4821-a2e8-75901621d36a.png)
![colors_08](https://user-images.githubusercontent.com/62002934/187067932-1bce9122-4489-49bd-89f5-9c125e26cb16.png)

**Comment by fwzuw** [comment]
看起来没什么问题
![image](https://user-images.githubusercontent.com/48246272/187068184-382859d6-6ee9-4757-892d-90cedb9ad8c6.png)
