### ISSUE TITLE
Bug反馈 512*512按问题 内设置构建三维结构时会导致闪退

### ISSUE THREAD

**Issue by bAdOoWindy** [ToKiNoBug/SlopeCraft#54]
### 我的操作
创建立体地图画 导入一张512*512的PNG图片 设置里
![图片](https://user-images.githubusercontent.com/4119845/195327157-7661bfca-80a6-42c6-a176-8719a1d747f2.png)
游戏版本选1.19 立体地图画
方块列表按cheep 优先混凝土 然后手动启用water
HSV 转换为地图画 导出为Litematic
![图片](https://user-images.githubusercontent.com/4119845/195327875-479e9ac8-167b-4546-85b2-8af6618709b7.png)
进度条走到接近尽头
程序就闪退了
### 我认为应当发生的事情
 导出完成

### 实际上发生的事情
在搭桥阶段 闪退 无任何报错

### 我导入到SlopeCraft中的原图

![图片](https://user-images.githubusercontent.com/4119845/195328465-fd332577-6305-4a2b-af68-3725d5252776.png)

### 其他
补充说明，进度条是在搭桥阶段闪退的。

**Comment by bAdOoWindy** [comment]
另外调整颜色那里，HSV算法如果用512*512就不会出现粉红色变黄色，用256就会
![图片](https://user-images.githubusercontent.com/4119845/195329899-186bd009-3b6a-44ea-bbba-abb053f100e0.png)

**Comment by ToKiNoBug** [comment]
已收到，我最近比较忙，晚上的时候我测试一下，尽快修复

**Comment by ToKiNoBug** [comment]
> 另外调整颜色那里，HSV算法出现粉红色变黄色 ![图片](https://user-images.githubusercontent.com/4119845/195329899-186bd009-3b6a-44ea-bbba-abb053f100e0.png)

这个是“正常现象”，HSV已经修复过了，它就这样，可能是亮度和饱和度的权重比较大，而色相的权重比较小。

**Comment by Cubik65536** [comment]
可以在不同平台上复现此问题，报错：

``` plain
Assertion failed: (m_impl.dimensions()[i] >= op.sizes()[i] + op.startIndices()[i]), function TensorEvaluator, file TensorMorphing.h, line 451.
[1]    6987 abort      ./SlopeCraft
```

**Comment by ToKiNoBug** [comment]
已修复
