### ISSUE TITLE
[BUG]一堆红石粉

### ISSUE THREAD

**Issue by 2X-ercha** [ToKiNoBug/SlopeCraft#6]
版本1.17
![QQ图片20210715103208](https://user-images.githubusercontent.com/72645310/125718845-c44e4bc2-9877-4258-a49a-8c660afa2db2.png)

**Comment by ToKiNoBug** [comment]
这个bug由“方块id”错位导致，在v3.4 RC1 中已经修复。如果仍然存在，欢迎反馈。
