### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by OOPPEENN** [ToKiNoBug/SlopeCraft#60]
最近有给空置域的地板铺上像素画的需求，Spritecraft的java应用没有1.19的新方块，网页版只能导出图片，施工非常不方便（大雾

尝试了一下Slope Craft，有一个缺点是颜色太少了，每个方块都有不同程度的颜色差异，能用上所有方块感觉画质能大幅提高（只针对直接观看的像素画

能否像Spritecraft一样能单独启用/禁用某个方块，而不是选择一个方块去代表某个颜色？

**Comment by ToKiNoBug** [comment]
这个功能我建议你用VisualCraft，它是我开发的视觉向像素画生成器，作为SpriteCraft的替代品。不过它到现在也只写完了界面和核心功能，我可用先发一个预览版。

另外我觉得你可能误解了平板地图画的用意。它和立体地图画类似，都是给地图用的，不是直接观看的，平板只是为了容易施工。

**Comment by ToKiNoBug** [comment]
你可以给我一个邮箱，或者qq号，我先发给你预览版，VisualCraft也需要宝贵的试用意见。我想在VisualCraft比较完善的时候，再在github上发布更新。

**Comment by OOPPEENN** [comment]
> 你可以给我一个邮箱，或者qq号，我先发给你预览版，VisualCraft也需要宝贵的试用意见。我想在VisualCraft比较完善的时候，再在github上发布更新。

OK的，非常感谢（a1004428886@126.com
