### ISSUE TITLE
特定图片无法转换

### ISSUE THREAD

**Issue by LucunJi** [ToKiNoBug/SlopeCraft#7]
设置：1.16 + File-only Map + Elegant + Lab
生成的图是全黑的。原图放在下面了。
![cholesky](https://user-images.githubusercontent.com/36262513/126197801-9f264a01-5e35-4604-a340-ae28ca9eb265.jpg)
![svd](https://user-images.githubusercontent.com/36262513/126197804-d54c42f1-0125-4795-92d6-b0523a0939ad.jpg)

**Comment by ToKiNoBug** [comment]
这个bug出现在哪个版本？是3.4的rc1吗

**Comment by ToKiNoBug** [comment]
按照你的选项，我用这张图片试了一下，图片转化结果正常。<br>
我猜测可能是软件没有载入颜色表：在出现这个bug之前，“Step 3/6 方块列表”界面的这些颜色框是不是都显示为异常的颜色？<br>
![未标题-1](https://user-images.githubusercontent.com/62002934/126249932-790132f8-0307-414e-8537-de1633013dee.png)

**Comment by ToKiNoBug** [comment]
我认为原因和#8 一样，可能是通过快捷方式调用，导致没有读取到颜色表导致的。最新的版本已经修复了这个bug。如果还有问题请继续反馈。
