### ISSUE TITLE
使用开始菜单搜索 (快捷方式) 打开软件会导致生成错误

### ISSUE THREAD

**Issue by Misaka-L** [ToKiNoBug/SlopeCraft#8]
### 使用设置
- 游戏版本: 1.16
- 地图画类型: 不可实装的地图画
- 预设方块列表: Vanilla
- 算法: RGB 优化  
> 由于以下图片在所有算法的表现上都很阴间，我就只放 "RGB 优化" 算法的生成结果了

源图 | "RGB 优化" 算法生成结果
------------ | -------------
![akari](https://user-images.githubusercontent.com/42287372/126202689-e9ba623b-0628-4217-b198-6159d1ad9150.jpg) | ![akari_output](https://user-images.githubusercontent.com/42287372/126203791-5373f9b0-523b-4cb1-91e7-c25b36902a13.png)
![Ptilopsis](https://user-images.githubusercontent.com/42287372/126203865-5d01a0fb-8fca-4874-a3b7-667e9befb60e.jpg) | ![Ptilopsis_output](https://user-images.githubusercontent.com/42287372/126204258-128fafe1-f509-4d10-aba1-f2f220fd2971.png)
![dark land](https://pixiv.cat/72873070.png) | ![dark land_output](https://user-images.githubusercontent.com/42287372/126206171-02138fd1-8807-435c-b91d-4b57063ebbc7.png)

> ~~另外可以赔偿我精神损失费吗~~

**Comment by ToKiNoBug** [comment]
有些电脑上用快捷方式打开会出现这个问题……因为没有找到存储颜色表的文件。不用快捷方式可以正常打开吗

**Comment by ToKiNoBug** [comment]
我认为可能是通过快捷方式调用，导致没有读取到颜色表导致的。最新的版本已经修复了这个bug。如果还有问题请继续反馈。
