### ISSUE TITLE
能否提供编译文档？

### ISSUE THREAD

**Issue by Trumeet** [ToKiNoBug/SlopeCraft#9]
作者您好，我希望在自己的设备上编译 SlopeCraft，但找不到任何编译方法或 Makefile 文件。请问能否提供编译文档以便本地编译？感谢！

**Comment by ToKiNoBug** [comment]
不知道你说的编译文档是什么？它们不能由qtcreator自动生成吗？

**Comment by Trumeet** [comment]
@ToKiNoBug 不懂 Qt，有没有什么如何编译的教程（比如 make 之类的），或者 Makefile 之类。

**Comment by ToKiNoBug** [comment]
> @ToKiNoBug 不懂 Qt 和 Qtcreator，有没有什么如何编译的教程（比如 make 之类的），或者 Makefile 之类。

我也只是会用……有一些头文件都是在编译的时候生成的，我也不清楚在其他环境里编译会缺什么……总之如果要编译，你肯定需要安装qt（6.0.4，更新的版本也可），没有gui库怎么可能编译嘛。

另外就是eigen库，因为很多工程都用到了eigen，我直接把它放在了本地，你只需要把eigen3.3.9（或更新版本）同样放在D盘里就行了。具体的路径可以看看.pro工程文件里是怎么配置的。

**Comment by Trumeet** [comment]
@ToKiNoBug 好吧，多谢回复。我自己研究一下如何编译，感谢作者。
